// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TRow: typeof import('tdesign-vue-next')['Row']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
    UChart: typeof import('./src/components/UChart.vue')['default']
    UFullCalendar: typeof import('./src/components/componentCalendar/UFullCalendar.vue')['default']
    UGantt: typeof import('./src/components/UGantt.vue')['default']
    UQuill: typeof import('./src/components/componentQuill/UQuill.vue')['default']
  }
}

export {}
