// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UChart: typeof import('./src/components/UChart.vue')['default']
    UFullCalendar: typeof import('./src/components/componentCalendar/UFullCalendar.vue')['default']
    UGantt: typeof import('./src/components/UGantt.vue')['default']
    UQuill: typeof import('./src/components/componentQuill/UQuill.vue')['default']
  }
}

export {}
